### ISSUE TITLE
Implement a refresh button

### ISSUE THREAD

**Issue by mattarnster** [mattarnster/radarr-uwp-app#2]
Implement a refresh button on all views where data is being fetched from the Radarr server.

The button should be the 'Refresh' icon from the iconset here:
https://docs.microsoft.com/en-us/windows/uwp/design/style/segoe-ui-symbol-font

Task is reserved for @FarshanAhamed

**Comment by mattarnster** [comment]
Thanks for this @FarshanAhamed. I'll be reviewing this PR this week, so you can get the Hacktoberfest credit.

**Comment by FarshanAhamed** [comment]
@mattarnster  Glad to help you.

**Comment by mattarnster** [comment]
@FarshanAhamed Thanks, your changes have been merged!
